--Projeto de wishlist (lista de desejos)
--Atividade do curso técnico Desenvolvimento de Sistemas
--Senai Informática São Paulo - 2019
--DDL - LINGUAGEM DE CRIAÇÃO DE DADOS

--CRIA BANCO DE DADOS DO PROGRAMA
CREATE DATABASE SENAI_WISHLIST_DESAFIO;

--CRIA A TABELA DE USUARIOS
CREATE TABLE USUARIOS (
	-- COLUNA TIPO_DADOS CARACTERÍSTICAS CHAVE
	ID	INT IDENTITY PRIMARY KEY
	,EMAIL VARCHAR(250) NOT NULL UNIQUE
	,SENHA VARCHAR(250) NOT NULL UNIQUE
);

--CRIA A TABELA DE DESEJOS
CREATE TABLE DESEJOS (
	-- COLUNA TIPO_DADOS CARACTERÍSTICAS CHAVE
	ID INT IDENTITY PRIMARY KEY
	,DESEJO VARCHAR(250) NOT NULL UNIQUE
	,DATA_CRIACAO DATE NOT NULL
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID)
);